// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchAndMatchTracks(arg1:string,arg2:Array<main.LocalTrack>):Promise<Array<main.MatchedTrack>>;

export function GenerateTemplateRenames(arg1:Array<main.LocalTrack>,arg2:string):Promise<Array<main.MatchedTrack>>;

export function ParseFilenamesWithAI(arg1:Array<string>,arg2:string):Promise<Array<main.AIParsedTrack>>;

export function RenameMatchedTracks(arg1:Array<main.MatchedTrack>):Promise<string>;

export function SelectFolder():Promise<Array<main.LocalTrack>>;
