// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchAndMatchTracks(arg1, arg2) {
  return window['go']['main']['App']['FetchAndMatchTracks'](arg1, arg2);
}

export function GenerateTemplateRenames(arg1, arg2) {
  return window['go']['main']['App']['GenerateTemplateRenames'](arg1, arg2);
}

export function ParseFilenamesWithAI(arg1, arg2) {
  return window['go']['main']['App']['ParseFilenamesWithAI'](arg1, arg2);
}

export function RenameMatchedTracks(arg1) {
  return window['go']['main']['App']['RenameMatchedTracks'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
